name: CI

on: push

env:
  up_tamer_commit: "5b6013aa3d56a8731147a442a831a81f73727d4d"
  up_pyperplan_commit: "b4fb924320af9f1870db51d20a925aa913255527"

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -m pip install -r dev-requirements.txt

      - name: Install tarski
        run: |
          python3 -m pip install tarski[arithmetic]
          sudo apt install -y gringo

      - name: Black check
        run: |
          python3 -m pip install black==22.6.0
          python3 -m black --check --exclude=unified_planning/grpc/generated/ .

      - name: MyPy check
        run: python3 -m mypy unified_planning

      - name: Test all packages imports
        run: python3 scripts/test_imports.py


  run-tests-ubuntu:
    runs-on: ubuntu-latest
    needs: [basic-check]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -m pip install -r dev-requirements.txt

      - name: Install tarski
        run: |
          python3 -m pip install tarski[arithmetic]
          sudo apt install -y gringo

      - name: Checkout up-tamer
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-tamer
          path: up-tamer
          ref: ${{env.up_tamer_commit}}

      - name: Install up-tamer
        run: python3 -m pip install up-tamer/

      - name: Checkout up-pyperplan
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-pyperplan
          path: up-pyperplan
          ref: ${{env.up_pyperplan_commit}}

      - name: Install up-pyperplan
        run: python3 -m pip install up-pyperplan/

      - name: Setup java for ENHSP
        uses: actions/setup-java@v2
        with:
            distribution: 'microsoft'
            java-version: '17'

      - name: Download and install ENHSP
        run: |
          git clone https://gitlab.com/enricos83/ENHSP-Public.git
          cd ENHSP-Public; git checkout enhsp20-0.9.3; ./compile; cd ..
          mkdir .planners; mv ENHSP-Public/enhsp-dist .planners/enhsp-20; rm -rf ENHSP-Public

      - name: Test code-snippets
        run: bash scripts/test_code_snippets.sh

      - name: Run tests
        run: bash run_tests.sh

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true


  run-tests-windows:
    runs-on: windows-latest
    needs: [basic-check]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -m pip install -r dev-requirements.txt

      - name: Checkout up-tamer
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-tamer
          path: up-tamer
          ref: ${{env.up_tamer_commit}}

      - name: Install up-tamer
        run: python3 -m pip install up-tamer/

      - name: Checkout up-pyperplan
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-pyperplan
          path: up-pyperplan
          ref: ${{env.up_pyperplan_commit}}

      - name: Install up-pyperplan
        run: python3 -m pip install up-pyperplan/

      - name: Setup java for ENHSP
        uses: actions/setup-java@v2
        with:
            distribution: 'microsoft'
            java-version: '17'

      - name: Download and install ENHSP
        run: |
          git clone https://gitlab.com/enricos83/ENHSP-Public.git
          cd ENHSP-Public; git checkout enhsp20-0.9.3; bash ./compile; cd ..
          bash -c "mkdir .planners; mv ENHSP-Public/enhsp-dist .planners/enhsp-20; rm -rf ENHSP-Public"

      - name: Run tests
        run: bash run_tests.sh


  run-tests-macos:
    runs-on: macos-latest
    needs: [basic-check]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -m pip install -r dev-requirements.txt

      - name: Install tarski
        run: |
          python3 -m pip install tarski[arithmetic]
#          brew install gringo -- Commented because not working on github actions

      - name: Checkout up-tamer
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-tamer
          path: up-tamer
          ref: ${{env.up_tamer_commit}}

      - name: Install up-tamer
        run: python3 -m pip install up-tamer/

      - name: Checkout up-pyperplan
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-pyperplan
          path: up-pyperplan
          ref: ${{env.up_pyperplan_commit}}

      - name: Install up-pyperplan
        run: python3 -m pip install up-pyperplan/

      - name: Setup java for ENHSP
        uses: actions/setup-java@v2
        with:
            distribution: 'microsoft'
            java-version: '17'

      - name: Download and install ENHSP
        run: |
          git clone https://gitlab.com/enricos83/ENHSP-Public.git
          cd ENHSP-Public; git checkout enhsp20-0.9.3; bash ./compile; cd ..
          bash -c "mkdir .planners; mv ENHSP-Public/enhsp-dist .planners/enhsp-20; rm -rf ENHSP-Public"

      - name: Run tests
        run: bash run_tests.sh


  check-protobuf:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Protobuf compiler
        run: |
          python3 -m pip install grpcio-tools==1.48.1

      - name: Check Protobuf generation
        run: bash scripts/generate_protobuf_bindings.sh

      - name: Check Protobuf bindings
        run: |
          echo "Checking that the committed protobuf bindings are exactly the one generated from the declaration"
          git diff --exit-code


  run-colab-notebooks:
    runs-on: ubuntu-latest
    needs: [basic-check, run-tests-ubuntu, run-tests-windows, run-tests-macos, check-protobuf] # We only test colabs if the base tests were succesful

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -m pip install -r dev-requirements.txt

      - name: Checkout up-tamer
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-tamer
          path: up-tamer
          ref: ${{env.up_tamer_commit}}

      - name: Install up-tamer
        run: python3 -m pip install up-tamer/

      - name: Checkout up-pyperplan
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-pyperplan
          path: up-pyperplan
          ref: ${{env.up_pyperplan_commit}}

      - name: Install up-pyperplan
        run: python3 -m pip install up-pyperplan/

      - name: Install jupyter and ipython3
        run: sudo apt install jupyter; sudo apt install ipython3

      - name: Run colabs
        run: bash scripts/test_colab.sh


  deploy-pypi:
    runs-on: ubuntu-latest
    needs: [basic-check, run-tests-ubuntu, run-tests-windows, run-tests-macos, check-protobuf, run-colab-notebooks] # We only deploy if the tests were successful
    if: github.ref == 'refs/heads/master' # We only deploy on master commits

    steps:
    - name: Checkout repo
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Make distrib
      run: |
        python3 -m pip install wheel
        bash scripts/make_distrib.sh

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
